### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by gitxmax** [qiwihui/plutus#1]
Hi qiwihui,
Seems like you doing some work at enhancing the original script.
I'm getting a couple of issues though.
Don't have any previous experience, with the telegram bot, so not sure, how to set it up properly, though I try everything possible..
In every case, I get the following error, running it with Python 3.8.5

`root@racknerd-64b3f5:~/plutus# python3 plutus.py
reading database: xxx  DONE
Traceback (most recent call last):
  File "plutus.py", line 161, in <module>
    send_telegram_message("Start searching bitcoin @ " + str(datetime.datetime.now()) + ', database size: ' + str(sum(len(i) for i in database)))
  File "/root/plutus/message.py", line 10, in send_telegram_message
    bot = Bot(token=token)
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 147, in __init__
    self.token = self._validate_token(token)
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 229, in _validate_token
    if any(x.isspace() for x in token):
TypeError: 'NoneType' object is not iterable

If I comment the telegram posting related lines and run the script, It goes through "reading database: ...  DONE`" part and the just sits there, doing nothing.

**Comment by qiwihui** [comment]
If you want to use telegram bot to send message, you need to set environment variable `TELEGRAM_CHAT_ID` for telegram channel ID, and `TELEGRAM_SENDER_TOKEN` for bot token.
In your situation, this is searching the database. I commented the print line to reduce no sense information. You can turn it on by uncomment the line `# print(str(address))`.

```py
	if address in database[0] or \
	   address in database[1] or \
	   address in database[2] or \
	   address in database[3]:
		with open('plutus.txt', 'a') as file:
			msg = ('hex private key: ' + str(private_key) + '\n' +
				   'WIF private key: ' + str(private_key_to_WIF(private_key)) + '\n' +
			      	   'public key: ' + str(public_key) + '\n' +
			           'address: ' + str(address) + '\n\n')
			send_telegram_message(msg)
			file.write(msg)
	else:
		pass
		# print(str(address))
```

**Comment by gitxmax** [comment]
Thanks,
TELEGRAM_SENDER_TOKEN inserted as the Fatherbot supplied.
For the TELEGRAM_CHAT_ID, I tried my own Telegram ID, a private group ID and a private channel ID, (of course, adding the telegram bot to them), yet, the error is there ... Also tried installing python 3.7.4, the error is the same.

I tried your solution, uncommenting # print(str(address)), it doesn't give any visible output, yet the script running and consuming ram ..

**Comment by qiwihui** [comment]
Please try to print token when call `send_telegram_message` in message.py to debug this error. It seems it cannot get token.
